# Generated by Django 2.2.4 on 2019-11-27 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20191127_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Bank_Name',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Bonus',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Cheque_Number',
            new_name='cheque_number',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Expenditure_Head',
            new_name='expenditure_head',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Payment_Method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='Penalty',
            new_name='penalty',
        ),
        migrations.RenameField(
            model_name='salarypayment',
            old_name='role',
            new_name='role_type',
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='school',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='employee',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='payment_To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ManagePayment',
        ),
    ]
