# Generated by Django 2.2.4 on 2019-11-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20191127_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='Payment_Method',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='Penalty',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='bank_Name',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='cheque_Number',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='expenditure_Head',
        ),
        migrations.RemoveField(
            model_name='monthlysalarypaid',
            name='over_time_total_hour',
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='bonus',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='expenditure_Head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.ExpenditureHead'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='month',
            field=models.CharField(default='April', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='over_time_amount',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='over_time_total_hour',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='penalty',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
    ]
