# Generated by Django 2.2.4 on 2019-11-27 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20191127_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
