# Generated by Django 2.2.4 on 2019-11-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_material_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takensubject',
            old_name='ca',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='takensubject',
            old_name='exam',
            new_name='eot',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Year'),
        ),
        migrations.AddField(
            model_name='takensubject',
            name='mot',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('O', 'O'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='takensubject',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('O', 'O'), ('F', 'F')], max_length=1),
        ),
        migrations.DeleteModel(
            name='SubjectAllocation',
        ),
    ]
