# Generated by Django 2.2.4 on 2019-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_present',
        ),
        migrations.AddField(
            model_name='employee',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
