# Generated by Django 2.2.4 on 2019-12-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20191203_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default=1, max_length=50)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Classroom')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'ordering': ['date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
