# Generated by Django 2.2.4 on 2019-12-05 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20191203_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidDues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.IntegerField(default=0)),
                ('Payment_Method', models.CharField(blank=True, max_length=100, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Cheque_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.RenameModel(
            old_name='Discount',
            new_name='Discounting',
        ),
        migrations.RemoveField(
            model_name='rolepermissions',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='absentemail',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='absentsms',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='bulkinvoice',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='bulkstudent',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('classroom',), 'verbose_name': ('classroom',), 'verbose_name_plural': 'classrooms'},
        ),
        migrations.AlterModelOptions(
            name='complain',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='duefeeemail',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='duefeesms',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='ebook',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'E-Book', 'verbose_name_plural': 'E-Books'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='emailsetting',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='employeeattendance',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='examattendance',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='examgrade',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='examschedule',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='examsuggestion',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='expenditure',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='expenditurehead',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='feetype',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='generatecertificate',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='hostelmember',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='incomehead',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='librarymember',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='manageuser',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('-timestamp',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='monthlysalarypaid',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='receive',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('day', 'start_time'), 'verbose_name': 'Routine', 'verbose_name_plural': 'Routine'},
        ),
        migrations.AlterModelOptions(
            name='salarygrade',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('school_name',), 'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ('section',), 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'SMS', 'verbose_name_plural': 'SMS'},
        ),
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='studenttype',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='superuser',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabus'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='transportmember',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'default_permissions': ('view', 'add', 'change', 'delete')},
        ),
        migrations.RenameField(
            model_name='feetype',
            old_name='classroom',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='feetype',
            old_name='classroom_amount',
            new_name='Class_Amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='bank_Name',
            new_name='Bank_Name',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='cheque_Number',
            new_name='Cheque_Number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_Method',
            new_name='Payment_Method',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='bank_name',
            new_name='Bank_Name',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='bonus',
            new_name='Bonus',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='cheque_number',
            new_name='Cheque_Number',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='expenditure_head',
            new_name='Expenditure_Head',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='month',
            new_name='Month',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='payment_method',
            new_name='Payment_Method',
        ),
        migrations.RenameField(
            model_name='salarygrade',
            old_name='penalty',
            new_name='Penalty',
        ),
        migrations.RenameField(
            model_name='salarypayment',
            old_name='role_type',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='discount',
            new_name='fees_discount',
        ),
        migrations.RenameField(
            model_name='studentpaidfees',
            old_name='bank_Name',
            new_name='Bank_Name',
        ),
        migrations.RenameField(
            model_name='studentpaidfees',
            old_name='cheque_Number',
            new_name='Cheque_Number',
        ),
        migrations.RenameField(
            model_name='studentpaidfees',
            old_name='payment_Method',
            new_name='Payment_Method',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='payment_To',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='Reporting',
            field=models.CharField(blank=True, choices=[('IH', 'Income_heads'), ('IM', 'Income_methods')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Bonus',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Expenditure_Head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.ExpenditureHead'),
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Month',
            field=models.CharField(default='November', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Payment_Method',
            field=models.CharField(default='Cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Penalty',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='over_time_total_hour',
            field=models.CharField(default=3000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Employee'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='studentpaidfees',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='expenditure_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='RolePermissions',
        ),
    ]
